### ISSUE TITLE
You can avoid Discord lib drama by telling that the library is meant for hardcores and not for n00bs.

### ISSUE THREAD

**Issue by Nefomemes** [vierofernando/discord-bot-lib#1]
So yea, one of the reason why Linux is better than Windows is that it's much more hardcore.

**Comment by vierofernando** [comment]
define "hardcore"

**Comment by Nefomemes** [comment]
Something much harder, in this context?

**Comment by vierofernando** [comment]
people can have their own opinions, also the definition of "hardcore" can vary among people.

**Comment by Nefomemes** [comment]
Hm yeah. But with a bit of explanation in the README, you can give an idea of what kind of "hardcore" you meant.

**Comment by vierofernando** [comment]
i've updated a readme a bit so it made sense
